# Generated by Django 2.2.1 on 2020-03-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payorder',
            name='order_number',
            field=models.CharField(max_length=36, unique=True, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='payorder',
            name='order_status',
            field=models.IntegerField(choices=[(1, '未支付'), (2, '已支付'), (3, '待发货'), (4, '已发货'), (5, '拒收'), (6, '已完成')], verbose_name='订单状态'),
        ),
        migrations.AlterModelTable(
            name='orderinfo',
            table='order_info',
        ),
    ]
