# Generated by Django 2.2.1 on 2020-02-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_auto_20200225_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='username',
            field=models.CharField(default='', max_length=32, verbose_name='用户名'),
        ),
    ]
