# Generated by Django 2.2.1 on 2020-02-25 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0003_loginuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginuser',
            name='user_type',
        ),
    ]
