# Generated by Django 2.2.1 on 2020-02-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0006_auto_20200226_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodstype',
            name='type_description',
            field=models.TextField(verbose_name='类型描述'),
        ),
    ]
