# Generated by Django 2.2.1 on 2020-02-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0008_auto_20200226_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_description',
            field=models.TextField(default='beautiful', verbose_name='商品描述'),
        ),
    ]
