# Generated by Django 2.2.1 on 2020-02-17 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tpye',
            new_name='type',
        ),
    ]
