# Generated by Django 2.2.1 on 2020-02-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20200217_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='picture',
            field=models.ImageField(default='22.jpg', upload_to='images', verbose_name='图片'),
        ),
    ]
